### ISSUE TITLE
Needed: Faster way to build and push image

### ISSUE THREAD

**Issue by alex-haddon** [DSCI-310-2025/dsci-310-group-11#7]
Because we are building and pushing two versions of the image for multi-platform usage, we should figure out if there is a way to speed up the build time.

**Comment by alex-haddon** [comment]
@chendaniely Just bumping this in your notifications. Thanks for the help!

**Comment by chendaniely** [comment]
Is there any particular reason why you're using these lines in the workflow file?

```yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

I also think the `platforms: linux/amd64,linux/arm64` line may be causing an issue. does it run within minutes (not hours) if you remove it?
